### ISSUE TITLE
Figure out best place to host public backups of the database?

### ISSUE THREAD

**Issue by maxcohn** [maxcohn/pka-db#6]
Maybe there is a good way to do it on GitHub? Currently the database is less than a megabyte, and the vast majority of data is already entered into it

**Comment by mdgilene** [comment]
If the db file really is small and you plan on sticking with sqlite, then yeah you can just throw them in a repository. If for some reason they start to get much larger you can enable  [git-lfs](https://git-lfs.github.com/) to better handle large files

**Comment by maxcohn** [comment]
I started hosting them as releases in this repo. I plan on doing monthly backups, and the March one is available now. Thanks!
