### ISSUE TITLE
Event Browsing and Ranking

### ISSUE THREAD

**Issue by mdgilene** [maxcohn/pka-db#9]
Feature Suggestion:

1. Episode/Event/Guest ranking through user votes. Think Reddit upvote/downvote.
1. Page to browse events without knowing exactly what you are looking for. (By Rank, By Guest, etc...)

**Comment by maxcohn** [comment]
For the time being, I'm want this to stay accountless, so having a ranking won't really work. I'm going to close the issue for now, but if anything changes, I'll reopen this.
